=== BastienJard/XML_project/assurance.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="compagnie" type="compagnieType">

        <xs:key name="agenceIDKey">
            <xs:selector xpath="agences/agence"/>
            <xs:field xpath="@idAgence"/>
        </xs:key>
        <xs:keyref name="conseillerAgenceAssociee" refer="agenceIDKey">
            <xs:selector xpath="employes/conseillers/conseiller/agenceAssociee"/>
            <xs:field xpath="@agenceId"/>
        </xs:keyref>
        <xs:keyref name="secretaireAgenceAssociee" refer="agenceIDKey">
            <xs:selector xpath="employes/secretaires/secretaire/agenceAssociee"/>
            <xs:field xpath="@agenceId"/>
        </xs:keyref>

    </xs:element>

    <xs:complexType name="compagnieType">
        <xs:sequence>
            <xs:element name="agences" type="agencesType"/>
            <xs:element name="clients" type="clientsType"/>
            <xs:element name="employes" type="employesType"/>
            <xs:element name="formules" type="formulesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="agencesType">
        <xs:sequence>
            <xs:element name="agence" type="agenceType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="agenceType">
        <xs:sequence>
            <xs:element name="ville" type="xs:string"/>
            <xs:element name="nom" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="idAgence" type="xs:int"/>
    </xs:complexType>


    <xs:complexType name="clientsType">
        <xs:sequence>
            <xs:element name="client" type="clientType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element name="etatcivil" type="etatcivilType"/>
            <xs:element name="contrats" type="contratsType"/>
        </xs:sequence>
        <xs:attribute name="idClient" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="contratsType">
    </xs:complexType>


    <xs:complexType name="formulesType">

    </xs:complexType>


    <xs:complexType name="employesType">
        <xs:sequence>
            <xs:element name="conseillers" type="conseillersType"/>
            <xs:element name="secretaires" type="secretairesType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="secretairesType">
        <xs:sequence>
            <xs:element name="secretaire" type="secretaireType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="conseillersType">
        <xs:sequence>
            <xs:element name="conseiller" type="conseillerType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="secretaireType">
        <xs:sequence>
            <xs:element name="agenceAssociee">
                <xs:complexType>
                    <xs:attribute name="agenceId" type="xs:int"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="etatcivil" type="etatcivilType"/>
            <xs:element name="salaire" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="idSecretaire" type="xs:int"/>
    </xs:complexType>


    <xs:complexType name="conseillerType">
        <xs:sequence>
            <xs:element name="agenceAssociee">
                    <xs:complexType>
                        <xs:attribute name="agenceId" type="xs:int"/>
                    </xs:complexType>
            </xs:element>
            <xs:element name="secretaireAssociee">
                <xs:complexType>
                    <xs:attribute name="secretaireId" type="xs:int"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="clientsAssociees" type="clientsAssocieesType"/>
            <xs:element name="etatcivil" type="etatcivilType"/>
            <xs:element name="salaire" type="xs:int"/>
        </xs:sequence>
        <xs:attribute name="idConseiller" type="xs:int"/>
    </xs:complexType>


    <xs:complexType name="clientsAssocieesType">
        <xs:sequence>
            <xs:element name="client" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="clientId" type="xs:int"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>





    <xs:complexType name="etatcivilType">
        <xs:all>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="prenom" type="xs:string"/>
            <xs:element name="naissance" type="DateType"/>
            <xs:element name="situation" type="situationType"/>
            <xs:element name="adresse" type="xs:string"/>
            <xs:element name="code_postal" type="codePostalType"/>
            <xs:element name="ville" type="xs:string"/>
            <xs:element name="pays" type="xs:string"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="telephone" type="telephoneType"/>
            <xs:element name="numeroSecuriteSociale" type="numeroSecuriteSocialeType"/>
        </xs:all>
    </xs:complexType>

    <xs:annotation>
        <xs:documentation>célibataire = cel, marié(e) = mar, veuf(ve) =veuf, divorcé(e) =div, paxé(e) = pax</xs:documentation>
    </xs:annotation>

    <xs:simpleType name="situationType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="mar"/>
            <xs:enumeration value="veuf"/>
            <xs:enumeration value="cel"/>
            <xs:enumeration value="div"/>
            <xs:enumeration value="pax"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:simpleType name="codePostalType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>



    <xs:simpleType name="DateType">
        <xs:restriction base="xs:string">
            <xs:pattern value="\d{2}/\d{2}/\d{4}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="telephoneType">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
            <xs:pattern value="([0-9][0-9] ){4}([0-9][0-9])" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="numeroSecuriteSocialeType">
        <xs:restriction base="xs:string">
            <xs:whiteSpace value="preserve"/>
            <xs:pattern value="[1|2] ([0-9][0-9] ){3}([0-9][0-9][0-9] ){2}([0-9][0-9])" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== BastienJard/XML_project/assurance.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="transfo1.xsl" ?>

<!--<!DOCTYPE cv SYSTEM "cv.dtd">-->

<compagnie xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="assurance.xsd">
    <agences>
        <agence idAgence="1">
            <ville>Monteton</ville>
            <nom>agence du centre</nom>
        </agence>
        <agence idAgence="2">
            <ville>Saint-Arnac</ville>
            <nom>agence tout risques</nom>
        </agence>
    </agences>

    <clients>
        <client idClient="1">
            <etatcivil>
                <nom>Jean</nom>
                <prenom>Serge</prenom>
                <naissance>10/02/1988</naissance>
                <situation>marié</situation>
                <adresse>21 avenue Colonel</adresse>
                <code_postal>06410</code_postal>
                <ville>Biot</ville>
                <pays>France</pays>
                <telephone>07 81 81 00 81</telephone>
                <email>serge.jean@gmail.com</email>
                <numeroSecuriteSociale>1 88 02 92 014 043 42</numeroSecuriteSociale>
            </etatcivil>
            <contrats>

            </contrats>
        </client>
    </clients>

    <employes>
        <conseilles>
            <conseille idConseille="1">
                <agenceAssociee agenceId="1"/>
                <secretaireAssociee secretaireID="1"/>
                <clientsAssossiees>
                    <client clientId="1"/>
                </clientsAssossiees>
                <etatcivil>
                    <nom>Dupont</nom>
                    <prenom>Alfred</prenom>
                    <naissance>14/04/1983</naissance>
                    <situation>célibataire</situation>
                    <adresse>chateau de</adresse>
                    <code_postal>55555</code_postal>
                    <ville>Moulinsart</ville>
                    <pays>France</pays>
                    <telephone>06 42 42 42 42</telephone>
                    <email>alfred.dupont@gmail.com</email>
                    <numeroSecuriteSociale>1 83 04 55 078 382 43</numeroSecuriteSociale>
                </etatcivil>
                <salaire>29400</salaire>
            </conseille>

        </conseilles>
        <secretaires>
            <secretaire idSecretaire="1">
                <agenceAssociee agenceId="1"/>
                <etatcivil>
                    <nom>Charles</nom>
                    <prenom>Micheline</prenom>
                    <naissance>16/06/1960</naissance>
                    <situation>mariée</situation>
                    <adresse>3 place du sol</adresse>
                    <code_postal>46800</code_postal>
                    <ville>Montcuq</ville>
                    <pays>France</pays>
                    <telephone>06 06 66 06 66</telephone>
                    <email>micheline.charles@gmail.com</email>
                    <numeroSecuriteSociale>2 60 06 16 780 372 50</numeroSecuriteSociale>
                </etatcivil>
                <salaire>22000</salaire>
            </secretaire>
        </secretaires>
    </employes>

    <formules>

    </formules>
</compagnie>
